---

- name: Get the Plex temporary password log
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      journalctl -u {{ plex_identifier }} | grep "A temporary password is provided for this session" | tail -n 1
  register: plex_temporary_password_log
  changed_when: false

- name: Print a warning if no Plex temporary password was found
  ansible.builtin.fail:
    msg: "No temporary password log entry found in the {{ plex_identifier }} service logs"
  when: plex_temporary_password_log.stdout == ""

- name: Print just the Plex temporary password
  ansible.builtin.debug:
    msg: "Your Plex temporary password is: {{ plex_temporary_password_log.stdout | regex_search('password is provided for this session: ([\\w]+)', '\\1') | first }}"
