---

- name: Fail if required Plex settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - plex_uid
    - plex_gid
    - plex_hostname

- name: Fail if Plex architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ plex_arch }}`) which is not currently supported.
      This Plex role also does not support self-building yet, so it's not possible to make use of it.
  when: "plex_arch not in ['amd64', 'arm64']"

- name: Validate Plex Traefik configuration
  when: plex_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Plex Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - plex_container_labels_traefik_hostname
        - plex_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `plex_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if plex_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          plex_container_labels_traefik_path_prefix (`{{ plex_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/plex`).
      when: "plex_container_labels_traefik_path_prefix != '/' and plex_container_labels_traefik_path_prefix[-1] == '/'"
